### ISSUE TITLE
Improve pNotUsedAsHeader

### ISSUE THREAD

**Issue by mlewand** [cksource/quail#1]
Currently `pNotUsedAsHeader` gives lots of false positives.
### Paragraph in a blockquote

``` html
<p>Foo.</p>

<blockquote>
<p>Bar.</p>
</blockquote>
```

Expected: 0 issues.

Actual: 1 issue.
### Paragraph after styled element

``` html
<table style="font-size:12.3199996948242px; line-height:1.5em;">
    <tbody>
        <tr>
            <td>
                <p>asd</p>
            </td>
        </tr>
    </tbody>
</table>

<p><strong>foo</strong> - bar baz bom.</p>
```

Expected: 0 issues.

Actual: 1 issue.

**Comment by mlewand** [comment]
The problem comes from [these lines](https://github.com/cksource/quail/blob/custom/src/js/custom/pNotUsedAsHeader.js#L29-38).

The issue here is that code checks **previous paragraph** (not caring about its DOM position) computed style, and if it differs in currently checked paragraph, then it's considered validation.

It's wrong, because often time we can have following case:

``` html
<style type="text/css">
article header {
    font-style: italic;
    font-family: Georgia, Times, "Times New Roman", serif;
}
</style>
<article>
    <header>
        <h1>Custom article title.</h1>

        <p>A short article introduction...</p>
    </header>

    <p>My awesome article.</p>

    <p>Foo bara</p>

    <footer>
        <p>
            Article published by...
        </p>
    </footer>
</article>
```

Paragraph in `<header>` has a different formatting, but it should not affect in any way paragraph with "My awesome article".

**Comment by fredck** [comment]
In general, checks shouldn't be done on styles but on the DOM structure. A11y standards and best practices are all about this.

**Comment by mlewand** [comment]
@fredck I can see the point for checking computed styles here:

It will catch the case if a paragraph is formatted (especially bolded) using classes or inline styles.

Consider:

``` html
<style type="text/css">.headline1{ font-weight: bolder; }</style>
<p class="headline1">What a beautiful headline.</p>

<p>...</p>
```

vs

``` html
<p><strong>What a beautiful headline.</strong></p>

<p>...</p>
```

I belive both cases should be reported as attempt to imitate headline.

**Comment by fredck** [comment]
I don't think so... only if the engine becomes a mind-reader :) 

My point is that how would you ever understand the semantics of that class by checking styles only? 

What if that class is used to mark a "attention" paragraph and that CSS decided that it should be bold for "styling" reasons. 

What if the next day the designer decides that that class should not be bold any more but big font... or italics... or colored... or whatever... or nothing. Then the engine will say that now everything is fine? It's senseless and inconsistent.

I keep with my opinion... checking styles is plain wrong... and I would say even amateurish in some cases.

**Comment by jessebeach** [comment]
What if we brought the testability down from `1` to `0.5` and flag this as a warning? I agree with fredck that Quail cannot read minds and the best we can do here is raise a potential issue, not a violation.

**Comment by fredck** [comment]
> What if we brought the testability down from 1 to 0.5 and flag this as a warning?

It makes sense for me.

**Comment by jessebeach** [comment]
Ok, this change has been made in tag 2.2.15: https://github.com/quailjs/quail/tree/2.2.15

**Comment by jessebeach** [comment]
@mlewand did you make your fix against the dev branch?

**Comment by mlewand** [comment]
We started customizations from the `master` branch.

But I can prepare the `dev` based branch for you and send a pull request so you can merge it with ease.

It's in [t/1b](https://github.com/cksource/quail/tree/t/1b) branch, resulted with pull request quailjs/quail#308.

**Comment by jessebeach** [comment]
Let's discuss this on our call tomorrow. Ideally I'd like you to be working
from a tag so we know exactly what code you are running. If it makes sense
we can cherry-pick commits into the master branch.

**Comment by mlewand** [comment]
Ok, this fix has been merged to Quail with [bf2839](https://github.com/quailjs/quail/commit/bf2839dde9e93612fec664389513b4720eb22895).
