### ISSUE TITLE
headerTooLong

### ISSUE THREAD

**Issue by mlewand** [cksource/quail#7]
# New Assessment
## Base Information

Rationale: "Check that heading markup is not used when content is not a heading.".

Testability: `1`

Techniques:
- [H42](https://github.com/cksource/quail-enhancement/blob/master/H42.md)
## Implementation
1. find all `h1-h6`
2. Check the innertext length, if it's longer than lets say `120` characters, fail the TC.

**Comment by mlewand** [comment]
Actually the better name would be `headerTextIsTooLong` that would be more consistent with `imgAltIsTooLong`.

**Comment by fredck** [comment]
As for the quick fix, the editor has a list of headers and this could be shown to the user in the balloon for her to decide which one to use (we may even propose a default one based on the context).

**Comment by mlewand** [comment]
In case of this assessment we already have a header, so we know everything. I think that here you'll referring to `pNotUsedAsHeader` Quick Fix that is about to come. : )

**Comment by mlewand** [comment]
Resulted with Quail PR quailjs/quail#326.
